language: node_js

# This (sudo: false) is needed to "run on container-based infrastructure" on
# which cache: is available
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

before_install: pip install --user flake8

before_script: npm install -g grunt-cli

script:
 - flake8 -v .
 - grunt jshint
 - python setup.py sdist install
